# Generated by Django 3.1.4 on 2020-12-30 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('decr', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('orgName', models.CharField(max_length=250)),
                ('slug', models.CharField(default='', max_length=100)),
                ('content', models.TextField()),
                ('cgpareq', models.FloatField(blank=True, default=None, null=True)),
                ('date', models.DateField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=30)),
                ('lname', models.CharField(default='', max_length=30)),
                ('roll', models.IntegerField(blank=True)),
                ('address', models.TextField()),
                ('branch', models.TextField()),
                ('sem', models.IntegerField(blank=True, default=None, null=True)),
                ('mobile', models.IntegerField(blank=True, default=None, null=True)),
                ('cgpa', models.FloatField(blank=True, default=None, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
